name: Nx Affected CI
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: yarn install
      - name: Run Affected Lint
        shell: bash
        run: yarn affected:lint -- --base=remotes/origin/master
      - name: Run Affected Tests
        shell: bash
        run: yarn affected:test -- --base=remotes/origin/master
      # - name: Run Affected e2e Tests
      #   shell: bash
      #   run: yarn affected:e2e -- --base=remotes/origin/master
      - name: Run build
        shell: bash
        run: yarn affected:build -- --base=remotes/origin/master