name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
          affected: 'true' # Defaults to true, therefore optional